// Code generated by "stringer -type=HistoryType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[BLELock-1]
	_ = x[BLEUnlock-2]
	_ = x[TimeChanged-3]
	_ = x[AutoLockUpdated-4]
	_ = x[MechSettingUpdated-5]
	_ = x[AutoLock-6]
	_ = x[ManualLocked-7]
	_ = x[ManualUnlocked-8]
	_ = x[ManualElse-9]
	_ = x[DriveLocked-10]
	_ = x[DriveUnlocked-11]
	_ = x[DriveFailed-12]
	_ = x[BLEAdvParameterUpdated-13]
}

const _HistoryType_name = "NoneBLELockBLEUnlockTimeChangedAutoLockUpdatedMechSettingUpdatedAutoLockManualLockedManualUnlockedManualElseDriveLockedDriveUnlockedDriveFailedBLEAdvParameterUpdated"

var _HistoryType_index = [...]uint8{0, 4, 11, 20, 31, 46, 64, 72, 84, 98, 108, 119, 132, 143, 165}

func (i HistoryType) String() string {
	if i < 0 || i >= HistoryType(len(_HistoryType_index)-1) {
		return "HistoryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HistoryType_name[_HistoryType_index[i]:_HistoryType_index[i+1]]
}
